services:
  - type: web
    name: statham-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 120

    envVars:
      - key: TG_TOKEN
        sync: false
      - key: TG_CHAT
        sync: false
      - key: TG_SIGNALS_TOPIC
        value: "6314"
      - key: TG_SESSIONS_TOPIC
        value: "1"
      - key: WEBHOOK_SECRET
        value: "statham_secret"
      - key: RENDER_SECRET
        generateValue: true
      - key: RENDER_URL
        sync: false
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      - key: BYBIT_TESTNET
        value: "false"
      - key: BYBIT_PAIRS
        value: "YBUSDT,ASTERUSDT,EDGEUSDT,STOUSDT"
      - key: BINGX_API_KEY
        sync: false
      - key: BINGX_API_SECRET
        sync: false
      - key: BINGX_PAIRS
        value: ""
      - key: ADMIN_IDS
        sync: false
      - key: DEFAULT_LEVERAGE
        value: "10"
      - key: DEFAULT_SIZE_USDT
        value: "1"
      - key: TRAIL_PCT
        value: "0.5"
      - key: PAIR_SETTINGS_JSON
        value: '{}'
      - key: DATA_DIR
        value: "/tmp"
